# Generated by Django 4.0.6 on 2022-08-04 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('086e93c6-bf7c-4916-8abd-431378d8bb05'), primary_key=True, serialize=False, unique=True),
        ),
    ]
