# Generated by Django 4.0.6 on 2022-08-09 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_created_at_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d91e808a-5840-4ab2-9aef-4c7da3a47c36'), primary_key=True, serialize=False, unique=True),
        ),
    ]
