# Generated by Django 4.0.6 on 2022-07-19 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('092c8300-cd75-4a16-931a-364ac02eae3f'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('image', models.FileField(upload_to='products/')),
                ('small_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=1)),
                ('total_quantity', models.IntegerField(default=1)),
                ('is_out_of_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
