# Generated by Django 4.0.6 on 2022-08-01 11:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('image', models.FileField(upload_to='products/')),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=1)),
                ('total_quantity', models.PositiveIntegerField(default=1)),
                ('is_out_of_stock', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.CharField(choices=[('home_appliances', 'Home Appliances'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('books', 'Books'), ('groceries', 'Groceries'), ('food_and_food_products', 'Food and Food Products'), ('jewelry', 'Jewelry'), ('toys', 'Toys')], max_length=125)),
                ('delivery_charge', models.PositiveIntegerField(default=40)),
                ('discount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('net_banking', 'Net Banking'), ('upi_payment', 'UPI Payment'), ('emi', 'EMI')], default='cash_on_delivery', max_length=125)),
                ('is_payed', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('total_price', models.IntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='booked', max_length=125)),
                ('shipped_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('out_for_delivery_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.product')),
            ],
        ),
    ]
