# Generated by Django 4.0.6 on 2022-08-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
    ]
