# Generated by Django 4.0.6 on 2022-07-19 13:26

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_id_alter_product_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fd9a1999-b998-4ebc-bc65-aff6f6a5145c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
