# Generated by Django 4.0.6 on 2022-07-19 13:27

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_added_date_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ea006622-f6ef-460a-9559-96e08c8c9136'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
