# Generated by Django 4.0.6 on 2022-07-19 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_added_date_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8e410bf9-4fe4-4b3f-9906-af91befa3b83'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
