# Generated by Django 4.0.6 on 2022-07-21 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_id_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_canceled',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ce0e682-527a-45ee-8eea-23f0d019d52d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
