# Generated by Django 4.0.6 on 2022-07-21 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_order_is_canceled_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4fa45eb6-a5e7-471c-a36e-70e485e40d47'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
